version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: deps
          command: make deps
      - restore_cache:
          key: go-cache
      - run:
          name: test
          command: make test-cover
      - save_cache:
          key: go-cache
          paths:
            - /go/pkg/mod/cache/download/
            - /go/bin/
