version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/nezorflame/speech-recognition-bot
    steps:
      - checkout
      - restore_cache:
          key: go-cache
      - run:
          name: Check dependencies
          command: make deps
      - run:
          name: Test with coverage
          command: make test-cover
      - save_cache:
          key: go-cache
          paths:
            - /go/pkg/mod/cache/download/
            - /go/bin/
